export const SETCOUNTRY                         = 'setcountry';
export const SETLANGUAGE                        = 'setlanguage';
export const SETPROFILES                        = 'setprofiles';
export const SET_REQUEST_FLIGHT_AVAIL           = 'SET_REQUEST_FLIGHT_AVAIL';
export const SET_FLIGHT_VALUES                  = 'SET_FLIGHT_VALUES'; // values trả về từ dữ liệu flightAvail.
export const SET_ITEM_FLIGHT_AVAIL              = 'SET_ITEM_FLIGHT_AVAIL'; // item khi xem chi tiết hoặc vào màn hình đặt.
export const SET_FLIGHT_HOLDER_CONTACT          = 'SET_FLIGHT_HOLDER_CONTACT'; // Thông tin liên hệ lúc đặt chuyến bay.
export const SET_FLIGHT_PAX                     = 'SET_FLIGHT_PAX'; // mảng thông tin khách hàng.
export const SET_VALUE_FILTER_FLIGHT            = 'SET_VALUE_FILTER_FLIGHT'; // dữ liệu hiển thị màn hình filter.
export const SET_LIST_CHILD                     = 'SET_LIST_CHILD'; // dữ liệu hiển thị màn hình filter.
export const SET_AVATAR                         = 'SET_AVATAR'; // Avatar account
export const SET_SUM_NOTIFY_THONGBAO            = 'SET_SUM_NOTIFY_THONGBAO'; // Tổng số notify thông báo chưa đọc
export const SET_SUM_NOTIFY_THUMOISUKIEN        = 'SET_SUM_NOTIFY_THUMOISUKIEN';// Tổng số notify thông báo chưa đọc
export const SET_SUM_NOTIFY_BAOBAI              = 'SET_SUM_NOTIFY_BAOBAI';
export const SET_LIST_CHILD_BAOBAI              = 'SET_LIST_CHILD_BAOBAI';
export const SET_LIST_CHILD_CHAT                = 'SET_LIST_CHILD_CHAT'; // Danh sách học sinh và số tn mới trong chat
export const SET_SUM_NOTIFY_ALL_APP             = 'SET_SUM_NOTIFY_ALL_APP'; // Tổng số tinh nhắn chưa đọc all app
export const SET_LIST_CHILD_THONGBAO_ALL        = 'SET_LIST_CHILD_THONGBAO_ALL';
export const SET_LIST_CHILD_THONGBAO            = 'SET_LIST_CHILD_THONGBAO';
export const SET_LIST_CHILD_THUMOISUKIEN        = 'SET_LIST_CHILD_THUMOISUKIEN';
export const SET_FULLNAME                       = 'SET_FULLNAME';
